[tool.poetry]
name = "qt-log"
version = "1.1.3"
description = "Qt Custom UI Log for Maya/Houdini"
authors = ["Maximiliano Rocamora <maxirocamora@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/MaxRocamora/QtLog"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
]

[tool.poetry.dependencies]
python = ">=3.7,<3.15"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
